### ISSUE TITLE
Blocky workspace button

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#46] opened 2024-10-18 10:15 UTC
4'th workspace button haven't been rounded after closing all apps in the 3 workspace
![image](https://github.com/user-attachments/assets/102dbfcb-3e56-4f49-a163-051b940b9539)

**Comment by AymanLyesri** [comment] 2024-10-18 10:31
Please specify the exact steps to reproduce this behavior, cause it works for me without issues

**Comment by michaelnotjackson** [comment] 2024-10-18 11:01
Hmmm. It is this way from the start of os

**Comment by AymanLyesri** [comment] 2024-10-18 11:58
I found out its also bugged for me in some cases, gonna be fixed in the next update

**Closed** 2024-10-18 14:59 UTC
Labels: bug
