### ISSUE TITLE
/home/$USER/%u no such file or dir

### ISSUE THREAD

**Issue by HinaHyugaHime** [AymanLyesri/hyprland-conf#102] opened 2024-11-07 23:50 UTC
![image](https://github.com/user-attachments/assets/d1bc81f6-0b85-4cf5-964e-472c2ff7cb90)
when clicking audio it gives this but we install pipewire

**Comment by HinaHyugaHime** [comment] 2024-11-08 01:19
also no idea where you set this but 
```file:///home/$USER/%u```
is bugging my browser and file explorer

**Comment by HinaHyugaHime** [comment] 2024-11-08 01:33
> ![image](https://private-user-images.githubusercontent.com/102651522/384176333-d1bc81f6-0b85-4cf5-964e-472c2ff7cb90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMjk4MzksIm5iZiI6MTczMTAyOTUzOSwicGF0aCI6Ii8xMDI2NTE1MjIvMzg0MTc2MzMzLWQxYmM4MWY2LTBiODUtNGNmNS05NjRlLTQ3MmMyZmY3Y2I5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMTMyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmNjZGU0NmU5ZGI2NWRmMmNhODZkMGRhMjdjYzY2NDU3MmY4ZTc2YTBjODYxYTYzMDJlMzBmYjc0MWZkZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.guSbHLd28Ade5PyNdkMvGnQMG933m774vCbUDY664_g) when clicking audio it gives this but we install pipewire

update to this part, installing pipewire-pulse and connecting the sockets and services to each other fixed it, still got the second issue though

**Comment by HinaHyugaHime** [comment] 2024-11-08 01:34
I got thunar working without this error but because it's using the thunar command not the desktop file, still get the firefox error when starting up firefox

> also no idea where you set this but `file:///home/$USER/%u` is bugging my browser and file explorer

**Comment by HinaHyugaHime** [comment] 2024-11-08 02:25
what I mean by this error btw 
![image](https://github.com/user-attachments/assets/cc305d04-ab0b-4b5e-84f4-cdabf2e01d29)

**Comment by HinaHyugaHime** [comment] 2024-11-08 02:25
same error on firefox

**Comment by HinaHyugaHime** [comment] 2024-11-08 16:30
It applies only to applications open with app search..

**Comment by michaelnotjackson** [comment] 2024-11-09 08:32
> It applies only to applications open with app search..

Best way to check if this issue is caused by app search script or smth else is to install alternative app launcher (smth like rofi) and check if when opening apps with it will cause same behavior

**Comment by michaelnotjackson** [comment] 2024-11-09 08:36
Hmm... Just noticed that when I'm opening Clion with ags app launcher, it tries to edit %U file and it's not happening then using rofi

**Comment by michaelnotjackson** [comment] 2024-11-09 08:48
I could find how you open apps, but from what app-search.sh outputs, I believe you are running them by manually parsing .desktop file for executable. You can try starting .desktop files via gtk-launch (instaleld with gtk3 package)

**Comment by michaelnotjackson** [comment] 2024-11-09 09:50
> > I could find how you open apps, but from what app-search.sh outputs
> 
> We've ditched the app-search script and adopted the default ags app query service, see [here](https://github.com/AymanLyesri/hyprland-conf/pull/96) So if it has a problem, its [aylur](https://github.com/Aylur/ags)'s fault

Ok. Now I understand how apps are searched, but do you mind giving reference to the part of code, that launches apps?

**Comment by AymanLyesri** [comment] 2024-11-09 10:08
https://github.com/AymanLyesri/hyprland-conf/blob/17f23e0cf7211f572b4d4cff5f687c95c75c2ac1/.config/ags/widgets/AppLauncher.ts#L151-L167

**Comment by michaelnotjackson** [comment] 2024-11-09 10:12
Fixed in PR

**Comment by AymanLyesri** [comment] 2024-11-09 10:17
@HinaHyugaHime update and let us know

**Comment by HinaHyugaHime** [comment] 2024-11-09 17:00
> @HinaHyugaHime update and let us know

ok yeah fixed now

**Closed** 2024-11-09 17:04 UTC
Labels: bug
