### ISSUE TITLE
Bug with visuals of wallpaper switcher

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#34] opened 2024-10-14 11:25 UTC
Trailing rectangles appear when cursor removed from workspace preview
![image](https://github.com/user-attachments/assets/67880f6f-8cdf-4e8f-bdf7-f7bd107dcd6d)

**Comment by AymanLyesri** [comment] 2024-10-14 12:33
I'll see what i can do, but my guess the problem is with hyprland compositor itself

**Comment by HinaHyugaHime** [comment] 2024-10-15 00:58
> I'll see what i can do, but my guess the problem is with hyprland compositor itself

gonna have to agree that this will be a difficult fix if he can, I also think it's the compositor in which case he can't fix that.

**Comment by AymanLyesri** [comment] 2024-10-15 08:32
The only "fix" i can think of is to minimize the animations that could cause this

**Comment by michaelnotjackson** [comment] 2024-10-15 16:23
> The only "fix" i can think of is to minimize the animations that could cause this

What is the expected behavior of these rectangles? Maybe I'll be able to fix it in my spare time

**Comment by AymanLyesri** [comment] 2024-10-15 17:20
> > The only "fix" i can think of is to minimize the animations that could cause this
> 
> What is the expected behavior of these rectangles? Maybe I'll be able to fix it in my spare time

to not show basically

**Comment by michaelnotjackson** [comment] 2024-10-15 17:28
> > > The only "fix" i can think of is to minimize the animations that could cause this
> > 
> > 
> > What is the expected behavior of these rectangles? Maybe I'll be able to fix it in my spare time
> 
> to not show basically

Yeah, but weren't they put in that place with some reason in mind? Like, maybe, creating colorful border or smth like that?

**Comment by AymanLyesri** [comment] 2024-10-15 18:05
>Yeah, but weren't they put in that place with some reason in mind? Like, maybe, creating colorful border or smth like that?

Nope, they are just artifacts of the layer when it moves or changes size.
when the layer is not moving or resizing, these artifacts never show.

**Comment by AymanLyesri** [comment] 2024-10-15 18:11
Found out the artifact changes color based on border size of current widget
![image](https://github.com/user-attachments/assets/a6b4e1bd-4111-4de3-9670-aea72a53da92)
So its either a problem with ags, gtk or hyprland layer itself

**Comment by AymanLyesri** [comment] 2024-10-21 20:55
I've minimized the animations that could cause this, closing the issue for now..

**Closed by AymanLyesri** 2024-10-21 20:55 UTC
Labels: bug
