### ISSUE TITLE
Problems using AGS on preexisting rice

### ISSUE THREAD

**Issue by msayuji** [AymanLyesri/hyprland-conf#80] opened 2024-10-27 08:30 UTC
Hello,
First off I want to say I really like your dotfiles, especially all the things you've made with AGS (they make me think of the config from [end-4](https://github.com/end-4/dots-hyprland).
I also want the fancy AGS bar and widgets but I can't get it to work on my preexisting environment.
Everytime I run ags & or just ags in the terminal with your config in my ~/.config/ags it tells me [the contents of this pastebin](https://pastebin.com/E6unyM9r).
I use prasanthrangan's dotfiles and because I don't know anything about typescript and struggle to understand the workings of AGS I can't solve this problem on my own and thought maybe someone could help.
I even tried asking AI but the ags folder is pretty large so I can't just paste the contens of the .ts files into the prompt.
I'm truly stuck and would really appreciate any help.
Thank you very much in advance

**Comment by msayuji** [comment] 2024-10-27 09:22
Okay I fixed it not launching at all by installing gvfs, fd and brightnessctl and dart-sass, which I didn't know I was missing (maybe add them as dependencies in the wiki page?). But now the bar It doesn't have blur. I installed the python-pywal from the arch repos, but when I do something a notification pops up telling me "bash: line 1: ...."(see image below). But when I looked in your dotfiles on github at ~/.config/hypr/configs/custom/ there was only a file called .gitkeep.
![image](https://github.com/user-attachments/assets/ab431a1f-2949-45e0-86ad-891b10db45e2)

And as I mentioned earlier, I use prasanthrangan's dots, which means that I use swww for wallpapers, is there any way to make your ags config change colors and blur with swww instead of hyprpaper?

(no blur in topbar and sidebar)
![image](https://github.com/user-attachments/assets/8ddfb93e-b8d3-4789-b18e-72b9e31cff37)

**Comment by AymanLyesri** [comment] 2024-10-27 09:37
> First off I want to say I really like your dotfiles, especially all the things you've made with AGS (they make me think of the config from [end-4](https://github.com/end-4/dots-hyprland).

Thank uu, it means a lot :)

> (com.github.Aylur.ags:894696): Gjs-Console-WARNING **: 21:48:17.577: Another notification daemon is already running: dunst

dunst is running, kill it, cause am using my own notification daemon powered by ags

>(com.github.Aylur.ags:894696): Gjs-CRITICAL **: 21:48:17.894: JS ERROR: TypeError: section.get_file() is null
applyCss/<@resource:///com/github/Aylur/ags/app.js:73:34
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
refreshCss@file:///tmp/ags/main.js:13:7
@file:///tmp/ags/main.js:2606:1
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
(com.github.Aylur.ags:894696): Gjs-Console-CRITICAL **: 21:48:17.895: Gtk.CssProviderError: <data>:1:0Expected a valid selector
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
refreshCss@file:///tmp/ags/main.js:13:7
@file:///tmp/ags/main.js:2606:1
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

this is caused by ags not finding pywal colors am pretty sure it was fixed

**Comment by AymanLyesri** [comment] 2024-10-27 09:42
> Okay I fixed it not launching at all by installing gvfs, fd and brightnessctl and dart-sass, which I didn't know I was missing (maybe add them as dependencies in the wiki page?).

U need to run the installer that will get u all the dependencies, did u read the README perhaps?

>  But now the bar It doesn't have blur.

the blur is dependent on hyprland configuration, am guessing u only copied ags dots so the blur wont work

My recommendation is to install the whole config, its guaranteed to work, and u wont risk anything, there is a backup feature in the installer

**Comment by msayuji** [comment] 2024-10-27 10:23
Okay I installed it via the script but now there are a few problems:
- sddm is not themed
- I can't select new wallpapers (I don't even know how it works, like is it supposed to be that all the workspaces have their own wallpaper? because mine doesn't change with workspace)
- ags is not themed/isn't colored, as in it's only brown like in the screenshots before

it still looks pretty much like this except blur now works
> (no blur in topbar and sidebar) ![image](https://private-user-images.githubusercontent.com/164744703/380483316-8ddfb93e-b8d3-4789-b18e-72b9e31cff37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjQ2ODgsIm5iZiI6MTczMDAyNDM4OCwicGF0aCI6Ii8xNjQ3NDQ3MDMvMzgwNDgzMzE2LThkZGZiOTNlLWI4ZDMtNDc4OS1iMThlLTcyYjllMzFjZmYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMDE5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTZjNGM4YjUwYTFiODE5Yzk5NzMzZWFhYzgxMjkyMDdhNWMzOThmYjY5ODk3OTA5YjBiMDM0OTQ0YWNjMTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-UVgieWzfqVWhHcoAHpwKJMsNWMIqHsmmQw6MDOPVCc)

**Comment by msayuji** [comment] 2024-10-27 10:30
When I open terminal it tells me:
cat: ~/.cache/wal/sequences: No such file or directory. 
Anything I'm missing?

oh and also i don't have zsh plugins installed, how do I get those?
Everytime I open terminal it tell me 
~/.zshrc:source:9: no such file or directory: /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
~/.zshrc:source:10: no such file or directory: /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
~/.zshrc:source:11: no such file or directory: /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
~/.zshrc:source:12: no such file or directory: /usr/share/zsh/plugins/zsh-sudo/sudo.plugin.zsh
~/.zshrc:source:13: no such file or directory: /usr/share/zsh/plugins/zsh-auto-notify/auto-notify.plugin.zsh
~/.zshrc:source:14: no such file or directory: /usr/share/zsh/plugins/fzf-tab-git/fzf-tab.plugin.zsh

**Comment by AymanLyesri** [comment] 2024-10-27 10:39
cause u didnt install the packages from the installer

**Comment by AymanLyesri** [comment] 2024-10-28 21:07
No updates, closing this issue..

**Closed** 2024-10-30 08:49 UTC
Labels: question
