### ISSUE TITLE
Style crash

### ISSUE THREAD

**Issue by michaelnotjackson** [AymanLyesri/hyprland-conf#59] opened 2024-10-21 13:13 UTC
As far as I understand at some point ags stops respecting scss. I wasn't able to determine what causes this kind of behavior.
![2024-10-21-140018_hyprshot](https://github.com/user-attachments/assets/3fbfed10-9c9d-4b6d-95e1-19c8f901928e)
Here is the sequence of my actions:
1) Start ags
2) Open  wallpaper switch menu (style crashed after little delay)

Here is the log: [ags.log](https://github.com/user-attachments/files/17461345/ags.log)

**Comment by michaelnotjackson** [comment] 2024-10-21 13:15
> As far as I understand at some point ags stops respecting scss. I wasn't able to determine what causes this kind of behavior. ![2024-10-21-140018_hyprshot](https://private-user-images.githubusercontent.com/46103889/378439457-3fbfed10-9c9d-4b6d-95e1-19c8f901928e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MTY3MTUsIm5iZiI6MTcyOTUxNjQxNSwicGF0aCI6Ii80NjEwMzg4OS8zNzg0Mzk0NTctM2ZiZmVkMTAtOWM5ZC00YjZkLTk1ZTEtMTljOGY5MDE5MjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDEzMTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYmQ4YTBiYzcxMDc0MjYyNjc4ZDQwMWQyNjBjNjQ5ZDk3ZmQ5NTc2NTgxNjVhNTkwYjcxNWE5ZTIwMGM4ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UgAH_jutZ19RAtTrTyd6hPRTlIZXKp1FSsJO-gUqgdU) Here is the sequence of my actions:
> 
>     1. Start ags
> 
>     2. Open  wallpaper switch menu (style crashed after little delay)
> 
> 
> Here is the log: [ags.log](https://github.com/user-attachments/files/17461345/ags.log)

It fixes if I click the reload button in wallpaper menu. Also wallpapers here are shifted by 1 workspace
![image](https://github.com/user-attachments/assets/cb1cb187-04b1-4ac2-94e7-064f3b74eeff)

**Comment by AymanLyesri** [comment] 2024-10-21 14:05
hmmm it works without issues on my desktop/laptop

try running `update` and restart ags

if the issue is still there, post the output of 
```
cat $HOME/.config/hypr/hyprpaper/config/defaults.conf 
```

**Comment by michaelnotjackson** [comment] 2024-10-21 14:21
Here it is. [defaults.conf.txt](https://github.com/user-attachments/files/17462297/defaults.conf.txt)
But now I can't make it appear with wallpaper switcher yet it appeared after running update and rebooting when I switched to 2 workspace and closed zen browser. This time it quickly disappeared by itself

**Comment by michaelnotjackson** [comment] 2024-10-21 14:25
> Here it is. [defaults.conf.txt](https://github.com/user-attachments/files/17462297/defaults.conf.txt) But now I can't make it appear with wallpaper switcher yet it appeared after running update and rebooting when I switched to 2 workspace and closed zen browser. This time it quickly disappeared by itself

This behavior is repeatable.  Here is new log: [ags.log](https://github.com/user-attachments/files/17462399/ags.log)

**Comment by AymanLyesri** [comment] 2024-10-21 15:24
>     1. Start ags
> 
>     2. Open  wallpaper switch menu (style crashed after little delay)

I couldnt reproduce it, it just works

> Here is new log: [ags.log](https://github.com/user-attachments/files/17462399/ags.log)

the log dosent say much about ur issue

> Here it is. [defaults.conf.txt](https://github.com/user-attachments/files/17462297/defaults.conf.txt)

the defaults look good, i dont get why u got wallpapers shifted

**last resort** try a clean installation of the config using the curl command
if the problem is still there we need someone else to confirm this behavior

**Comment by HinaHyugaHime** [comment] 2024-10-22 04:25
> hmmm it works without issues on my desktop/laptop
> 
> try running `update` and restart ags
> 
> if the issue is still there, post the output of
> 
> ```
> cat $HOME/.config/hypr/hyprpaper/config/defaults.conf 
> ```

try running the install.sh in the readme and retrying you might be too outdated to run update

**Comment by AymanLyesri** [comment] 2024-10-23 15:33
No updates, closing this issue..

**Comment by michaelnotjackson** [comment] 2024-10-24 18:16
Hi. Sorry for inactivity, my laptop charger broke, had to wait until the new one arrived. Reinstalled whole system. Now ags is crashing before anything can show up. Here is new log:  [ags.log](https://github.com/user-attachments/files/17511171/ags.log)

**Comment by AymanLyesri** [comment] 2024-10-24 19:50
from the logs, its an error with css file not working, am pretty sure its the pywal file in .cache directory.
when it dosent exist or emty, ags wont launch, I've made a hotfix, update and let me know.

**Comment by michaelnotjackson** [comment] 2024-10-24 20:12
> from the logs, its an error with css file not working, am pretty sure its the pywal file in .cache directory. when it dosent exist or empty, ags wont launch, I've made a hotfix, update and let me know.

It is fixed now. Thanks!

**Closed** 2024-10-24 20:40 UTC
Labels: bug
